version: '3'

services:

  # nginx:
  #   image: nginx:mainline-alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/config/:/etc/nginx/conf
  #     - /etc/letsencrypt/:/etc/letsencrypt/
  #     - ./nginx/logs/:/var/log/nginx/
  #   environment:
  #     - NGINX_HOST=multinet.app
  #     - NGINX_PORT=80
  #   network_mode: "host"


  arangodb:
    image: arangodb/arangodb:3.4.3
    command: >
      sh -c "apk add curl && arangod"
    container_name: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_PASSWORD}
    volumes:
      - "${ARANGO_DATA}:/var/lib/arangodb3"
      - "${ARANGO_DATA_APPS}:/var/lib/arangodb-apps"
    network_mode: "host"
    healthcheck:
      test: curl -I -X GET http://localhost:8529/_db/_system/_admin/aardvark/index.html#login || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    restart: on-failure


  multinet-server:
    build: ./multinet-server/
    container_name: multinet-server
    network_mode: "host"
    healthcheck:
      test: curl --fail -s http://localhost:5000/ || exit 1
      interval: 2m
      timeout: 10s
      retries: 3
    restart: on-failure

  
  multinet-client:
    build: ./multinet-client/
    container_name: multinet-client
    network_mode: "host"
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 2m
      timeout: 10s
      retries: 3
    restart: on-failure


  view-nodelink:
    build: ./view-nodelink/
    container_name: view-nodelink
    network_mode: "host"
    healthcheck:
      test: curl --fail -s http://localhost:8081/ || exit 1
      interval: 2m
      timeout: 10s
      retries: 3
    restart: on-failure


  view-adjmatrix:
    build: ./view-adjmatrix/
    container_name: view-adjmatrix
    network_mode: "host"
    healthcheck:
      test: curl --fail -s http://localhost:8082/ || exit 1
      interval: 2m
      timeout: 10s
      retries: 3
    restart: on-failure
    