- name: Clone adjmatrix repository
  git:
    repo: https://github.com/multinet-app/view-adjmatrix.git
    dest: "{{ adjmatrix_client_path }}"
  register: adjmatrix_git

- name: Install adjmatrix dependencies
  yarn:
    path: "{{ adjmatrix_client_path }}"
  when: adjmatrix_git.changed

- name: Build adjmatrix app
  command: yarn run build
  args:
    chdir: "{{ adjmatrix_client_path }}"
  environment:
    PUBLIC_PATH: "/{{adjmatrix_client_path}}/"
  when: adjmatrix_git.changed
