- name: Install multinet client side app dependencies
  yarn:
    path: "{{ multinet_client_path }}"
  when: multinet_git.changed

- name: Set up .env file
  copy:
    src: "{{ multinet_client_path }}/.env.default"
    dest: "{{ multinet_client_path }}/.env"
    remote_src: yes

- name: Inject git sha into .env file
  lineinfile:
    path: "{{ multinet_client_path }}/.env"
    regexp: "^VUE_APP_GIT_SHA="
    line: "VUE_APP_GIT_SHA=$(git rev-parse HEAD)"

- name: Inject ga tag into .env file
  lineinfile:
    path: "{{ multinet_client_path }}/.env"
    regexp: "^VUE_APP_GA_TAG="
    line: "VUE_APP_GA_TAG={{ ga_tag }}"

- name: Specify multinet api URL
  lineinfile:
    path: "{{ multinet_client_path }}/.env"
    regexp: "^VUE_APP_MULTINET_HOST="
    line: "VUE_APP_MULTINET_HOST=multinet.app"

- name: Build multinet client side
  command: yarn run build
  args:
    chdir: "{{ multinet_client_path }}"
  when: multinet_git.changed
