- name: Install multinet client side app dependencies
  yarn:
    path: "{{ multinet_server_path }}/client"
  when: multinet_git.changed

- name: Generate git-sha file for use in client build
  shell: "git rev-parse HEAD >git-sha"
  args:
    chdir: "{{ multinet_server_path }}/client"
  when: multinet_git.changed

- name: Build multinet client side
  command: yarn run build
  args:
    chdir: "{{ multinet_server_path }}/client"
  when: multinet_git.changed

