- name: Install python3.7 and pip
  apt:
    pkg:
      - python3.7
      - python3.7-dev
      - python3.7-venv
      - python3-pip
    update_cache: true
  become: true

- name: Clone multinet server repository
  git:
    repo: https://github.com/multinet-app/multinet.git
    force: true
    dest: "{{ multinet_server_path }}"
  register: multinet_git

- name: Install service (systemd)
  template:
    src: "multinet.service.j2"
    dest: "/etc/systemd/system/multinet.service"
  become: true

- name: Reload units (systemd)
  systemd:
    name: multinet
    daemon_reload: true
  become: true

- name: Stop service (systemd)
  systemd:
    name: multinet
    state: stopped
  become: true

- name: Install python server dependencies
  command: pipenv install
  args:
    chdir: "{{ multinet_server_path }}"
  when: multinet_git.changed

- name: Set up .env file
  copy:
    src: "{{ multinet_server_path }}/.env.default"
    dest: "{{ multinet_server_path }}/.env"
    remote_src: yes

- name: Inject Sentry DSN into .env file
  lineinfile:
    path: "{{ multinet_server_path }}/.env"
    regexp: "^SENTRY_DSN="
    line: "SENTRY_DSN=${{secrets.SENTRY_DSN}}"

- name: (Re)start service (systemd)
  systemd:
    name: multinet
    state: restarted
  become: true

- name: Enable/Disable multinet service on boot
  service:
    name: multinet
    enabled: true
  become: true
