# https://www.arangodb.com/download-major/ubuntu/

- name: Add arangodb release key
  apt_key:
    url: https://download.arangodb.com/arangodb35/DEBIAN/Release.key
    state: present
  become: true

- name: Create arangodb list file
  shell: echo 'deb https://download.arangodb.com/arangodb35/DEBIAN/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list
  become: true

- name: Install arangodb dependency
  apt:
    name: apt-transport-https
    update_cache: true
  become: true

- name: Install arangodb
  apt:
    name: arangodb3=3.5.2-1
  become: true

- name: Start arangodb service
  systemd:
    name: arangodb3
    state: restarted
  become: true
