- name: Install certbot
  apt:
    name: [certbot, python-certbot-nginx]
    update_cache: true
  become: true

- name: echo CERT_ADMIN_EMAIL
  shell: echo {{CERT_ADMIN_EMAIL}}

- name: Request a cert
  shell: certbot --nginx -m {{ CERT_ADMIN_EMAIL }} -d multinet.app --agree-tos -n
  become: true
  creates: "/etc/letsencrypt/live/multinet.app/fullchain.pem"
  vars:
    CERT_ADMIN_EMAIL: "{{ lookup('env','CERT_ADMIN_EMAIL') }}"

- name: Reload nginx
  systemd:
    name: nginx
    state: restarted
  become: true