---
- hosts: all
  remote_user: root

  vars:
    ansible_python_interpreter: /usr/bin/python3
    multinet_server_path: "{{ ansible_env.HOME }}/multinet"

  roles:
    - role: oefenweb.yarn
      become: true
    - role: geerlingguy.nginx
      become: true
    - role: leesoh.pipenv
      become: true

  tasks:
    - include_tasks: server_tasks.yml
