---
- hosts: all
  remote_user: root

  vars:
    ansible_python_interpreter: /usr/bin/python3
    multinet_server_path: "{{ ansible_env.HOME }}/multinet"
    adjmatrix_client_path: "{{ ansible_env.HOME }}/adjmatrix"
    nodelink_client_path: "{{ ansible_env.HOME }}/nodelink"
    arangodb_password: "letmein"

  roles:
    - role: geerlingguy.nodejs
      become: true
    - role: oefenweb.yarn
      become: true
    - role: leesoh.pipenv
      become: true
    - role: geerlingguy.nginx
      vars:
        nginx_vhosts:
          - listen: "8080"
            server_name: "example.com"
            extra_parameters: |
              location /nodelink {
                alias {{ nodelink_client_path }}/src;
              }
              location /adjmatrix {
                alias {{ adjmatrix_client_path }}/src;
              }
              location /api {
                include uwsgi_params;
                uwsgi_pass unix:{{ multinet_server_path }}/multinet.sock;
              }
              location / {
                root {{ multinet_server_path }}/client/dist;
              }
      become: true

  tasks:
    - include_tasks: tasks/arangodb_tasks.yml
    - include_tasks: tasks/server_tasks.yml
    - include_tasks: tasks/client_tasks.yml
    - include_tasks: tasks/nodelink_tasks.yml
    - include_tasks: tasks/adjmatrix_tasks.yml
