---
- hosts: all
  remote_user: root

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: oefenweb.yarn
      become: true
    - role: geerlingguy.nginx
      become: true

  tasks:
    - name: Install python3 and pip
      apt:
        pkg:
          - python3-dev
          - python3-pip
          - python3-venv
        update_cache: true
      become: true

    - name: Install flask and uwsgi
      pip:
        name:
          - flask
          - uwsgi
        executable: /usr/bin/pip3
