- name: Install python3 and pip
  apt:
    pkg:
      - python3-dev
      - python3-pip
      - python3-venv
    update_cache: true
  become: true

- name: Install python dependencies
  pip:
    name:
      - flask
      - uwsgi
    executable: /usr/bin/pip3

- name: Clone multinet server repository
  git:
    repo: https://github.com/multinet-app/multinet.git
    dest: "{{ multinet_server_path }}"

- name: Install python server dependencies
  command: pipenv install --python /usr/bin/python3
  args:
    chdir: "{{ multinet_server_path }}"
