name: Deploy multinet
on: [repository_dispatch, push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Dump event
        run: jq . $GITHUB_EVENT_PATH

      - name: Make ssh key
        run: mkdir -p ~/.ssh && touch ~/.ssh/testing.pem && echo "${{secrets.TESTING_PEM}}" > ~/.ssh/testing.pem && chmod 400 ~/.ssh/testing.pem
          
      - uses: actions/checkout@v2
      - name: Install ansible roles
        run: ansible-galaxy install -r /home/runner/work/multinet-deploy/multinet-deploy/ansible/requirements.yml

      - name: Add server to known hosts
        run:  touch ~/.ssh/known_hosts && ssh-keyscan 18.217.253.44 >> ~/.ssh/known_hosts

      - name: Create security group for this runner
        run: AWS_ACCESS_KEY_ID={{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY={{ secrets.AWS_SECRET_ACCESS_KEY }} AWS_DEFAULT_REGION={{ secrets.AWS_DEFAULT_REGION }} AWS_INSTANCE_ID={{ secrets.AWS_INSTANCE_ID }} AWS_VPC_ID={{ secrets.AWS_VPC_ID }} /home/runner/work/multinet-deploy/multinet-deploy/scripts/create_security_group.sh

      - name: Deploy to testing environment
        run: ansible-playbook -i 18.217.253.44, /home/runner/work/multinet-deploy/multinet-deploy/ansible/playbook.yml --ssh-extra-args="-i ~/.ssh/testing.pem"

      - name: Create security group for this runner
        run: AWS_ACCESS_KEY_ID={{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY={{ secrets.AWS_SECRET_ACCESS_KEY }} AWS_DEFAULT_REGION={{ secrets.AWS_DEFAULT_REGION }} AWS_INSTANCE_ID={{ secrets.AWS_INSTANCE_ID }} AWS_VPC_ID={{ secrets.AWS_VPC_ID }}  /home/runner/work/multinet-deploy/multinet-deploy/scripts/destroy_security_group.sh

      