name: Deploy multinet
on: [repository_dispatch, push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Dump event
        run: jq . $GITHUB_EVENT_PATH

      - name: Make ssh key
        run: mkdir -p ~/.ssh && touch ~/.ssh/testing.pem && echo "${{secrets.TESTING_PEM}}" > ~/.ssh/testing.pem && chmod 400 ~/.ssh/testing.pem
          
      - uses: actions/checkout@v2
      - name: Deploy to testing environment
        run: ls ~/ && ansible-playbook -i 18.217.253.44, /home/runner/work/multinet-deploy/multinet-deploy/ansible/playbook.yml --ssh-extra-args="-i ~/.ssh/testing.pem"